### ISSUE TITLE
Clicking the button crashes Chrome

### ISSUE THREAD

**Issue by prometheas** [prometheas/jira-2-omnifocus#23]

**Comment by steinbrueckri** [comment]
any updates on the issues?

**Comment by steinbrueckri** [comment]
Thanks for the detailed feedback.  I'll check it out as well.  😅

**Comment by macintacos** [comment]
I was just thinking about how much I would love it if there was an extension like this, so if you need some more motivation I'm here to give it 😄

**Comment by macintacos** [comment]
So, funnily enough... I cloned this repo and built the extension just to take a crack at it (opened #24 because of some installation errors but got over that hump), and then loaded it into Chrome directly, and... the extension works just fine after that. The button was definitely crashing chrome before, but it isn't after I built it from source.

It seems like the one in the store is the one that has this bug, since whatever is latest doesn't seem to be a problem. For reference, I built the project with the following version of `node`/`npm`:

```
   installed : v8.17.0 (with npm 6.13.4)
```

The commit history goes up until April 27th, 2017, but the Chrome web store says the latest version was released in September of 2016. [There seems to have been quite a few commits between those two dates](https://github.com/prometheas/jira-2-omnifocus/compare/1.1.2...master) that might account for this behavior being fixed. 

@prometheas perhaps all you need to do is release a new version with the latest from `master`?

**Comment by prometheas** [comment]
Thanks for all the moral support, gang 🙏🏼❤️ will try to give this a go tonight.

**Comment by prometheas** [comment]
Well, I've submitted 1.2 to the Chrome Web Store, and it's awaiting review. I've set a reminder to follow up when I get notification of approval.

**Comment by prometheas** [comment]
Not that I received any email notification about it, but Google has approved the updated extension 🎉

I'm going to resolve this ticket for now, but please have a look and let me know with a follow-up comment here if anyone out there is continuing to have this problem with the new 1.2 release of the extension.

⚠️ Note: since fixing this issue, I have come to learn that the Atlassian-hosted version of Jira has updated the page markup such that the selector string I'm using to identify the container into which the extension adds the button is no longer valid, causing the button not to render 😭 (see #28 for more info).

**Comment by steinbrueckri** [comment]
Maybe it helps somebody, I use this snippet for now.

Copy this and create a bookmark from it.
'''sh
javascript:window.location='omnifocus:///add?autoadd=true&autosave=true&due=today&note='+encodeURIComponent(window.location)+'&name='+encodeURIComponent(document.title)
'''

![image](https://user-images.githubusercontent.com/578303/89773430-2bd5b780-db04-11ea-9f98-8510ca0742ad.png)

**Comment by prometheas** [comment]
@steinbrueckri - may I ask you to elaborate a bit? Are you reporting continued trouble with the 1.2 update? If so, can you please describe the nature of this trouble?
